apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.apps.mongo.pvc.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.apps.mongo.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.apps.mongo.pvc.storage }}
