apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_USER: {{ .Values.secrets.mongoUser | quote }}
  MONGO_PASS: {{ .Values.secrets.mongoPass | quote }}
  MONGO_HOST: {{ .Values.secrets.mongoHost | quote }}
  MONGO_PORT: {{ .Values.secrets.mongoPort | quote }}
  MONGO_DB: {{ .Values.secrets.mongoDB | quote }}
  MONGO_AUTH_DB: {{ .Values.secrets.mongoAuthDB | quote }}
