apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_USER: {{ required "secrets.mongoUser is required" .Values.secrets.mongoUser | quote }}
  MONGO_PASS: {{ required "secrets.mongoPass is required" .Values.secrets.mongoPass | quote }}
  MONGO_HOST: {{ required "secrets.mongoHost is required" .Values.secrets.mongoHost | quote }}
  MONGO_PORT: {{ required "secrets.mongoPort is required" .Values.secrets.mongoPort | quote }}
  MONGO_DB: {{ required "secrets.mongoDB is required" .Values.secrets.mongoDB | quote }}
  MONGO_AUTH_DB: {{ required "secrets.mongoAuthDB is required" .Values.secrets.mongoAuthDB | quote }}
