{{- range $name, $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $app.port }}
      targetPort: {{ $app.port }}
      {{- if $app.service.nodePort }}
      nodePort: {{ $app.service.nodePort }}
      {{- end }}
  type: {{ $app.service.type }}
  {{- if $app.service.clusterIP }}
  clusterIP: {{ $app.service.clusterIP }}
  {{- end }}
{{- end }}
