apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: samarthfunde45/weather-backend:IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_PASS
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_DB
            - name: MONGO_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_AUTH_DB
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /metrics  
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
