name: App CI/CD

on:
  push:
    branches: ["master"]

env:
  BACKEND_IMAGE: samarthfunde45/weather-backend
  FRONTEND_IMAGE: samarthfunde45/weather-frontend
  VERSION: v${{ github.run_number }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  
  # JOB 1: Detect which files changed
 
  detect-changes:
    name: Detect Changes
    runs-on: self-hosted
    outputs:
      backend:  ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      k8s:      ${{ steps.filter.outputs.k8s }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Check which paths changed
        uses: dorny/paths-filter@v4.0.1
        id: filter
        with:
          base: master
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            k8s:
              - 'k8s/**'


  # JOB 2: SonarCloud Code Quality Scan
  # Runs before building — scans source code
  
  sonarcloud:
    name: SonarCloud Code Scan
    runs-on: self-hosted
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.backend == 'true' ||
      needs.detect-changes.outputs.frontend == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io


  # JOB 3: Build Backend (local only, no push)

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    needs: [detect-changes, sonarcloud]
    if: |
      always() && !cancelled() &&
      needs.detect-changes.outputs.backend == 'true' &&
      needs.sonarcloud.result != 'failure'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build Backend Image (local only)
        uses: docker/build-push-action@v7.1.0
        with:
          context: ./backend
          push: false
          load: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }}

 
  # JOB 4: Build Frontend (local only, no push)
 
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    needs: [detect-changes, sonarcloud]
    if: |
      always() && !cancelled() &&
      needs.detect-changes.outputs.frontend == 'true' &&
      needs.sonarcloud.result != 'failure'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build Frontend Image (local only)
        uses: docker/build-push-action@v7.1.0
        with:
          context: ./frontend
          push: false
          load: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }}

 
  # JOB 5: Trivy Security Scan,  Scans LOCAL images BEFORE pushing to DockerHub,  If CRITICAL found → pipeline fails, nothing pushed

  trivy-scan:
    name: Trivy Security Scan
    runs-on: self-hosted
    needs: [detect-changes, build-backend, build-frontend]
    if: |
      always() && !cancelled() &&
      (
        needs.build-backend.result  == 'success' ||
        needs.build-frontend.result == 'success'
      )

    steps:
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: ${{ runner.os }}-trivy-db

      - name: Trivy — Scan Backend Image
        if: needs.build-backend.result == 'success'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          trivyignores: .trivyignore
          severity: CRITICAL,HIGH
          timeout: 10m

      - name: Trivy — Scan Frontend Image
        if: needs.build-frontend.result == 'success'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          trivyignores: .trivyignore
          severity: CRITICAL,HIGH
          timeout: 10m

 
  # JOB 6: Push to DockerHub, Only runs if Trivy scan passed
  
  push-images:
    name: Push to DockerHub
    runs-on: self-hosted
    needs: [detect-changes, build-backend, build-frontend, trivy-scan]
    if: |
      always() && !cancelled() &&
      needs.trivy-scan.result == 'success' &&
      (
        needs.build-backend.result  == 'success' ||
        needs.build-frontend.result == 'success'
      )

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image to DockerHub
        if: needs.build-backend.result == 'success'
        run: |
          docker push ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }}
          docker tag ${{ env.BACKEND_IMAGE }}:${{ env.VERSION }} ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.BACKEND_IMAGE }}:latest

      - name: Push Frontend Image to DockerHub
        if: needs.build-frontend.result == 'success'
        run: |
          docker push ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }}
          docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }} ${{ env.FRONTEND_IMAGE }}:latest
          docker push ${{ env.FRONTEND_IMAGE }}:latest

 
  # JOB 7: Deploy to Kubernetes, Runs after clean push to DockerHub
 
  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: [detect-changes, push-images, build-backend, build-frontend]
    if: |
      always() && !cancelled() &&
      (
        needs.build-backend.result  == 'success' ||
        needs.build-frontend.result == 'success' ||
        needs.detect-changes.outputs.k8s == 'true'
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Create App Secrets in Kubernetes
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=MONGO_USER=${{ secrets.MONGO_USER }} \
            --from-literal=MONGO_PASS=${{ secrets.MONGO_PASS }} \
            --from-literal=MONGO_HOST=${{ secrets.MONGO_HOST }} \
            --from-literal=MONGO_PORT=${{ secrets.MONGO_PORT }} \
            --from-literal=MONGO_DB=${{ secrets.MONGO_DB }} \
            --from-literal=MONGO_AUTH_DB=${{ secrets.MONGO_AUTH_DB }} \
            --namespace=weather-app \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Namespace
        run: kubectl apply -f k8s/namespace.yml

      - name: Apply App Manifests
        run: kubectl apply -f k8s/app/

      - name: Update Backend Image
        if: needs.build-backend.result == 'success'
        run: |
          kubectl set image deployment/backend \
            backend=${{ env.BACKEND_IMAGE }}:${{ env.VERSION }} \
            -n weather-app

      - name: Update Frontend Image
        if: needs.build-frontend.result == 'success'
        run: |
          kubectl set image deployment/frontend \
            frontend=${{ env.FRONTEND_IMAGE }}:${{ env.VERSION }} \
            -n weather-app

      - name: Wait for Backend Rollout
        if: needs.build-backend.result == 'success'
        run: kubectl rollout status deployment/backend -n weather-app --timeout=120s

      - name: Wait for Frontend Rollout
        if: needs.build-frontend.result == 'success'
        run: kubectl rollout status deployment/frontend -n weather-app --timeout=180s

      - name: Verify All Pods
        run: kubectl get pods -n weather-app
